SEED: 1
T_END: 2.0
LINEAR: False
STEREO: True
NOISE: True
SP_METHOD_PROC: "gh"
SP_METHOD_MEAS: "gh"
CUB_ORDER: 3
MAP_INIT: False
TIME_IT: False
STEP_TOL: 1.0e-08
# ESGVI params
VERBOSE: True
MAX_ITERS: 10
BACK_ITERS: 10
INIT_STEP_SIZE: 1.0e0
# Noise Params
PROC_NOISE: "gaussian"
MEAS_NOISE: "skew_laplace"
MAP_LOSS_FUN: "cauchy"
GVI_LOSS_FUN: "skew_laplace"
GVI_SKEW_LAMBDA: 0.1
GVI_T_DOF: 3.0
# Script Params
SAVE_FIGS: False
SHOW_FIGS: True