dataset: "se2"

P0_mult: 1e-3
R0_mult: 1e-2

# se2
Q0_mult: [0.01, 0.1, 0.05]
# 2D
# Q0_mult: [0.1, 0.1]


# se2
x0_pos: [0, 0, 0]
# 2D
# x0_pos: [0, 0]

anchor_pos: [[2, 1], [0, 1], [2, 0]]

proc_model: "single_integrator"
meas_model: "range_point"

save_figs: False
show_figs: True
export: True