# Parameters for SE2 Localization Example

# Simulation Params
SEED: 1
T_END: 2.0
MEAS_MODEL: "range_point" # "range_pose" # "relative_pos"
NOISE: true
USE_FIT: false
SP_METHOD_PROC: "gh" # Sigma point method for process/prior factors.
SP_METHOD_MEAS: "gh" # Sigma point method for measurement factors.
CUB_ORDER: 3
MAP_INIT: false
TIME_IT: false

# ESGVI Params
VERBOSE: true
MAX_ITERS: 5
BACK_ITERS: 0
INIT_STEP_SIZE: 1e0
STEP_TOL: 1e-8

# Script Params
SAVE_FIGS: false
SHOW_FIGS: true